// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgcEA5aSgznV-sGU5D2lTSuE4oUVoQks0',
    appId: '1:810451883674:web:2b927fc0e61b049bc8f123',
    messagingSenderId: '810451883674',
    projectId: 'clone-11abd',
    authDomain: 'clone-11abd.firebaseapp.com',
    storageBucket: 'clone-11abd.appspot.com',
    measurementId: 'G-PEKRGJ4F98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA986lc1W7daqoI_SQjjPlIO9h2wpMXBs',
    appId: '1:810451883674:android:8b03cb1fab34baddc8f123',
    messagingSenderId: '810451883674',
    projectId: 'clone-11abd',
    storageBucket: 'clone-11abd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBStOlJRpm33tTeu5v8iseAhxgu2xEGfEg',
    appId: '1:810451883674:ios:07352f3034c21fcfc8f123',
    messagingSenderId: '810451883674',
    projectId: 'clone-11abd',
    storageBucket: 'clone-11abd.appspot.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBStOlJRpm33tTeu5v8iseAhxgu2xEGfEg',
    appId: '1:810451883674:ios:07352f3034c21fcfc8f123',
    messagingSenderId: '810451883674',
    projectId: 'clone-11abd',
    storageBucket: 'clone-11abd.appspot.com',
    iosBundleId: 'com.example.amazonClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgcEA5aSgznV-sGU5D2lTSuE4oUVoQks0',
    appId: '1:810451883674:web:25f78416bb1fb1ddc8f123',
    messagingSenderId: '810451883674',
    projectId: 'clone-11abd',
    authDomain: 'clone-11abd.firebaseapp.com',
    storageBucket: 'clone-11abd.appspot.com',
    measurementId: 'G-WZ0JBN3929',
  );
}
